### ISSUE TITLE
Capitalize string in JS won't work.

### ISSUE THREAD

**Issue by HendrikJan** [KelliePetersen/javascript-python-comparison#3]
Hey. Not sure if you are still maintaining this list. Thanks for having this list.
I'm quite experienced with JavaScript, never touched Python, but after reading this list I want to learn Python <3.

Anyway, I noticed an fault in the JavaScript examples.

`string[0].toUpperCase();` will just return the first character capitalized.

Instead you can do this: `string[0].toUpperCase() + string.substring(1);`

**Comment by KelliePetersen** [comment]
Just saw this now! Thank you, updated
